// flow-typed signature: 18fbd4a5cee8838db9775691257860f5
// flow-typed version: <<STUB>>/react-native-style-tachyons_v^3.5.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-style-tachyons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-style-tachyons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-style-tachyons/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/reactWrapper' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/absolute' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/borders' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/flexbox' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/fontWeights' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/heights' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/images' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/lineHeight' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/opacity' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/spacing' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/text' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/tracked' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/typeScale' {
  declare module.exports: any;
}

declare module 'react-native-style-tachyons/lib/styles/widths' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-style-tachyons/lib/index.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/index'>;
}
declare module 'react-native-style-tachyons/lib/reactWrapper.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/reactWrapper'>;
}
declare module 'react-native-style-tachyons/lib/styles/absolute.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/absolute'>;
}
declare module 'react-native-style-tachyons/lib/styles/borders.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/borders'>;
}
declare module 'react-native-style-tachyons/lib/styles/flexbox.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/flexbox'>;
}
declare module 'react-native-style-tachyons/lib/styles/fontWeights.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/fontWeights'>;
}
declare module 'react-native-style-tachyons/lib/styles/heights.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/heights'>;
}
declare module 'react-native-style-tachyons/lib/styles/images.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/images'>;
}
declare module 'react-native-style-tachyons/lib/styles/lineHeight.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/lineHeight'>;
}
declare module 'react-native-style-tachyons/lib/styles/opacity.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/opacity'>;
}
declare module 'react-native-style-tachyons/lib/styles/spacing.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/spacing'>;
}
declare module 'react-native-style-tachyons/lib/styles/text.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/text'>;
}
declare module 'react-native-style-tachyons/lib/styles/tracked.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/tracked'>;
}
declare module 'react-native-style-tachyons/lib/styles/typeScale.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/typeScale'>;
}
declare module 'react-native-style-tachyons/lib/styles/widths.js' {
  declare module.exports: $Exports<'react-native-style-tachyons/lib/styles/widths'>;
}
