// flow-typed signature: d9a3a583c1a4c15739a5c1370f6d07b3
// flow-typed version: <<STUB>>/update-creator_v^1.1.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'update-creator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'update-creator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'update-creator/dist/index' {
  declare module.exports: any;
}

declare module 'update-creator/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'update-creator/dist/index.js' {
  declare module.exports: $Exports<'update-creator/dist/index'>;
}
declare module 'update-creator/src/index.js' {
  declare module.exports: $Exports<'update-creator/src/index'>;
}
