version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: yarn test:ci
      - run:
          name: Post Stats To CodeCov
          command: bash <(curl -s https://codecov.io/bash)
